spring:
  config:
    import: optional:file:.env[.properties]
  
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/splitdebtdb;MODE=PostgreSQL;AUTO_SERVER=TRUE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080