-- SplitDebt schema used by the Spring Boot API.
-- The statements are intentionally CREATE TABLE IF NOT EXISTS so the API can run
-- against an existing PostgreSQL/Supabase database that already contains these tables.
-- The column names and relationships follow the supplied database schema and the SRS/PTTKHT.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    invite_code VARCHAR(64) NOT NULL UNIQUE,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_groups_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('OWNER','MEMBER')),
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_group_members_group FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT fk_group_members_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    icon VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    category_id BIGINT,
    payer_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    total_amount NUMERIC(19,4) NOT NULL CHECK (total_amount > 0),
    expense_date DATE NOT NULL,
    receipt_url TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_expenses_group FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT fk_expenses_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_expenses_payer FOREIGN KEY (payer_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS expense_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    split_type VARCHAR(30) NOT NULL,
    amount NUMERIC(19,4),
    percentage NUMERIC(8,4),
    weight NUMERIC(19,4),
    CONSTRAINT fk_expense_participants_expense FOREIGN KEY (expense_id) REFERENCES expenses(id),
    CONSTRAINT fk_expense_participants_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS expense_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id BIGINT NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    quantity NUMERIC(19,4) NOT NULL DEFAULT 1,
    unit_price NUMERIC(19,4) NOT NULL,
    total_price NUMERIC(19,4) NOT NULL,
    CONSTRAINT fk_expense_items_expense FOREIGN KEY (expense_id) REFERENCES expenses(id)
);

CREATE TABLE IF NOT EXISTS item_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    share_amount NUMERIC(19,4) NOT NULL,
    CONSTRAINT fk_item_participants_item FOREIGN KEY (item_id) REFERENCES expense_items(id),
    CONSTRAINT fk_item_participants_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    debtor_id BIGINT NOT NULL,
    creditor_id BIGINT NOT NULL,
    amount NUMERIC(19,4) NOT NULL CHECK (amount >= 0),
    source_type VARCHAR(40),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_debts_group FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT fk_debts_debtor FOREIGN KEY (debtor_id) REFERENCES users(id),
    CONSTRAINT fk_debts_creditor FOREIGN KEY (creditor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    debtor_id BIGINT NOT NULL,
    creditor_id BIGINT NOT NULL,
    amount NUMERIC(19,4) NOT NULL CHECK (amount > 0),
    status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING','PAID','CONFIRMED','CANCELLED')),
    payment_method VARCHAR(50),
    requested_at TIMESTAMP,
    paid_at TIMESTAMP,
    confirmed_at TIMESTAMP,
    CONSTRAINT fk_settlements_group FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT fk_settlements_debtor FOREIGN KEY (debtor_id) REFERENCES users(id),
    CONSTRAINT fk_settlements_creditor FOREIGN KEY (creditor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Compatibility table present in the supplied database. The new API primarily uses
-- expense_participants, but also mirrors computed shares here for compatibility.
CREATE TABLE IF NOT EXISTS expense_shares (
    expense_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    amount NUMERIC(19,4) NOT NULL CHECK (amount >= 0),
    PRIMARY KEY (expense_id, user_id),
    CONSTRAINT expense_shares_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES expenses(id),
    CONSTRAINT expense_shares_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS group_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    auto_freeze_day INTEGER,
    cloud_storage_sync VARCHAR(30) NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    decimal_scale INTEGER NOT NULL,
    image_optimization_enabled BOOLEAN NOT NULL,
    monthly_budget_limit NUMERIC(19,4),
    smart_settlement_enabled BOOLEAN NOT NULL,
    group_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_group_settings_group FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE IF NOT EXISTS user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    biometrics_enabled BOOLEAN NOT NULL,
    language VARCHAR(20) NOT NULL,
    notify_on_debt_reminder BOOLEAN NOT NULL,
    notify_on_new_expense BOOLEAN NOT NULL,
    notify_on_settlement BOOLEAN NOT NULL,
    theme VARCHAR(20) NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_groups_owner_id ON groups(owner_id);
CREATE INDEX IF NOT EXISTS idx_group_members_group_id ON group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_group_members_user_id ON group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_expenses_group_id ON expenses(group_id);
CREATE INDEX IF NOT EXISTS idx_expenses_payer_id ON expenses(payer_id);
CREATE INDEX IF NOT EXISTS idx_expenses_category_id ON expenses(category_id);
CREATE INDEX IF NOT EXISTS idx_expense_participants_expense_id ON expense_participants(expense_id);
CREATE INDEX IF NOT EXISTS idx_expense_participants_user_id ON expense_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_expense_items_expense_id ON expense_items(expense_id);
CREATE INDEX IF NOT EXISTS idx_item_participants_item_id ON item_participants(item_id);
CREATE INDEX IF NOT EXISTS idx_item_participants_user_id ON item_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_debts_group_id ON debts(group_id);
CREATE INDEX IF NOT EXISTS idx_debts_debtor_id ON debts(debtor_id);
CREATE INDEX IF NOT EXISTS idx_debts_creditor_id ON debts(creditor_id);
CREATE INDEX IF NOT EXISTS idx_settlements_group_id ON settlements(group_id);
CREATE INDEX IF NOT EXISTS idx_settlements_debtor_id ON settlements(debtor_id);
CREATE INDEX IF NOT EXISTS idx_settlements_creditor_id ON settlements(creditor_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);

INSERT INTO categories(name,icon)
SELECT 'Ăn uống','restaurant' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Ăn uống');
INSERT INTO categories(name,icon)
SELECT 'Di chuyển','directions_car' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Di chuyển');
INSERT INTO categories(name,icon)
SELECT 'Mua sắm','shopping_bag' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Mua sắm');
INSERT INTO categories(name,icon)
SELECT 'Khách sạn','hotel' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Khách sạn');
INSERT INTO categories(name,icon)
SELECT 'Giải trí','movie' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Giải trí');
INSERT INTO categories(name,icon)
SELECT 'Khác','category' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Khác');
