// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdiMdo7cvmdEjj_3k063RV-AAj0l6A-7s',
    appId: '1:534922111462:web:52cf4fa91bf487425f4e27',
    messagingSenderId: '534922111462',
    projectId: 'splitdebt-8c3fa',
    authDomain: 'splitdebt-8c3fa.firebaseapp.com',
    storageBucket: 'splitdebt-8c3fa.firebasestorage.app',
    measurementId: 'G-V7PJSRN5M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDBXRlrbAkJnE-7ixBt37CdbmvXTQy-M',
    appId: '1:534922111462:android:cfb4ee1a8e84391a5f4e27',
    messagingSenderId: '534922111462',
    projectId: 'splitdebt-8c3fa',
    storageBucket: 'splitdebt-8c3fa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_5Df91Sb-OtYiyNDSEL8-FEgv3W93mmg',
    appId: '1:280691561510:ios:6e73693c93c486f0c002e7',
    messagingSenderId: '280691561510',
    projectId: 'phela-8533d',
    storageBucket: 'phela-8533d.firebasestorage.app',
    iosClientId:
        '280691561510-4gq3t07oc9su7bpcs7b9uqthde0gk17o.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitDebt',
  );
}
